name: KSOC Check CI
on:
    # Triggers the workflow on push request on the main branch for changes in the specified paths. 
    push:
      branches:
        - main
jobs:
  ksoc-guard:
    permissions:
      contents: read
      security-events: write      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: KSOC Guard
        uses: ksoclabs/guard-action@v0.0.10
        with:
          fail_on_severity: high
          format: sarif
          ksoc_account_id: 2KW0CKZCYADZH5AL7TuFyoaIlvh
          ksoc_access_key_id: ${{ secrets.KSOC_ACCESS_KEY_ID }}
          ksoc_secret_key: ${{ secrets.KSOC_SECRET_KEY }}
      - name: Upload Image Scan SARIF Report
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
    
