name: KSOC Guard
on:
    # Triggers the workflow on push request on the main branch for changes in the specified paths.   
    push:
      branches:
        - main
jobs:
  ksoc-guard:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: KSOC Guard
        id: ksoc-guard
        uses: ksoclabs/guard-action@v0.0.10
        with:
          fail_on_severity: none
          ksoc_account_id: 2KW0CKZCYADZH5AL7TuFyoaIlvh
          ksoc_access_key_id: ${{ secrets.KSOC_ACCESS_KEY_ID }}
          ksoc_secret_key: ${{ secrets.KSOC_SECRET_KEY }}

